version: '3'
services:
  app:
    image: clip_service_container:1.0.0
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus.yml
    command:
      - '--config.file=/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - "8000:3000"
