version: "3"

services:
  server:
    image: clip_service_container:1.0.0
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./bento/prometheus.yml:/prometheus.yml
    command:
      - "--config.file=/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "8000:3000"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:80"
